dev: update cicd (#9)

diff --git a/bin/dev-lab-kind b/bin/dev-lab-kind
--- a/bin/dev-lab-kind
+++ b/bin/dev-lab-kind
@@ -1,24 +1,41 @@
 #!/usr/bin/env bash
+#######################################
+# Dev / Lab / Kind / Open sandbox environment
 #
-# Open sandbox environment
+# * Version: 1.0.0
 #
-# * Template: 1.3.0
+#######################################
+# Copyright [2023] [serdigital64@gmail.com]
 #
+# Licensed under the Apache License, Version 2.0 (the "License");
+# you may not use this file except in compliance with the License.
+# You may obtain a copy of the License at
+#
+#     http://www.apache.org/licenses/LICENSE-2.0
+#
+# Unless required by applicable law or agreed to in writing, software
+# distributed under the License is distributed on an "AS IS" BASIS,
+# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+# See the License for the specific language governing permissions and
+# limitations under the License.
+#######################################
 
 #
 # Imports
 #
 
 # shellcheck source=bin/dev-set
-source ./bin/dev-set || exit 1
-# shellcheck source=lib/bl64/bashlib64.bash
-source "${DEV_CICD_BASHLIB64}/bashlib64.bash" || exit 1
-
-#
-# Functions
-#
-
-declare DEV_LAB_KUBE_HOME="${HOME}/.kube"
+source ./bin/dev-set || { echo 'dev-set:Error: unable to load dev environment' 2>&1 && exit 1; }
+# shellcheck source-path=bin
+source ./bin/dev-env-kind || exit 1
+# shellcheck source-path=lib/bl64
+source "${DEV_LIB_BASHLIB64_TARGET}/bashlib64-module-txt.bash" &&
+  source "${DEV_LIB_BASHLIB64_TARGET}/bashlib64-module-fmt.bash" &&
+  source "${DEV_LIB_BASHLIB64_TARGET}/bashlib64-module-fs.bash" &&
+  source "${DEV_LIB_BASHLIB64_TARGET}/bashlib64-module-rnd.bash" &&
+  source "${DEV_LIB_BASHLIB64_TARGET}/bashlib64-module-iam.bash" &&
+  source "${DEV_LIB_BASHLIB64_TARGET}/bashlib64-module-cnt.bash" &&
+  source "${DEV_LIB_BASHLIB64_TARGET}/bashlib64-core.bash" || exit 1
 
 #
 # Functions
@@ -26,38 +43,44 @@ declare DEV_LAB_KUBE_HOME="${HOME}/.kube"
 
 function dev_lab_open() {
   bl64_dbg_app_show_function "$@"
-  local dev_lab_path_source='/source'
-  local dev_lab_path_project='/project'
-  local dev_lab_path_credentials='/credentials'
-  local dev_lab_entrypoint="${dev_lab_path_project}/bin/dev-lab-entrypoint"
+  local dev_lab_image="$1"
 
-  bl64_msg_show_task "open container sanbox (${dev_lab_image})"
+  bl64_msg_show_warning "temporary opening kubeconfig path permissions (${DEV_ENV_KIND_PATH_KUBE})"
+  bl64_fs_fix_permissions '0644' '0755' "${DEV_ENV_KIND_PATH_KUBE}"
+
+  bl64_msg_show_task "open sanbox environment (${dev_lab_image})"
   bl64_cnt_run_interactive \
     --network=host \
-    --entrypoint="$dev_lab_entrypoint" \
-    --env "DEV_LAB_USER=$(bl64_iam_user_get_current)" \
-    --env "DEV_TMP=/tmp" \
-    --mount "type=bind,source=${DEV_SRC},target=${dev_lab_path_source},readonly" \
-    --mount "type=bind,source=${DEV_ROOT},target=${dev_lab_path_project},readonly" \
-    --mount "type=bind,source=${DEV_ROOT}/vault,target=${dev_lab_path_project}/vault" \
-    --mount "type=bind,source=${DEV_LAB_KUBE_HOME},target=${dev_lab_path_credentials}/.kube,readonly" \
-    "${DEV_CICD_LAB_REGISTRY}/${dev_lab_image}"
+    --entrypoint="$DEV_LAB_KIND_CONTAINER_ENTRYPOINT" \
+    --workdir="$DEV_ENV_KIND_CONTAINER_PATH_ROOT" \
+    --env "_DEV_LAB_KIND_CONTAINER_USER=$(bl64_iam_user_get_current)" \
+    --env "DEV_PATH_TMP=/tmp" \
+    --mount "type=bind,source=${DEV_PATH_SRC},target=${DEV_ENV_KIND_CONTAINER_PATH_SRC},readonly" \
+    --mount "type=bind,source=${DEV_PATH_ROOT},target=${DEV_ENV_KIND_CONTAINER_PATH_ROOT},readonly" \
+    --mount "type=bind,source=${DEV_PATH_VAULT},target=${DEV_ENV_KIND_CONTAINER_PATH_VAULT}" \
+    --mount "type=bind,source=${DEV_ENV_KIND_PATH_KUBE},target=${DEV_ENV_KIND_CONTAINER_PATH_CREDENTIALS},readonly" \
+    "${DEV_ENV_KIND_REGISTRY}/${dev_lab_image}"
+
+  bl64_msg_show_task "closing kubeconfig path permissions (${DEV_ENV_KIND_PATH_KUBE})"
+  bl64_fs_fix_permissions '0600' '0700' "${DEV_ENV_KIND_PATH_KUBE}"
+}
+
+function dev_lab_initialize() {
+  bl64_dbg_app_show_function
+  bl64_check_directory "$DEV_ENV_KIND_PATH_KUBE" &&
+    bl64_cnt_setup
 }
 
 #
 # Main
 #
 
-declare dev_lab_image="${1:-$DEV_CICD_LAB_IMAGE}"
+declare dev_lab_image="${1:-${DEV_LAB_KIND_IMAGE}}"
 
 [[ -n "$DEV_CICD_DEBUG" ]] && bl64_dbg_all_enable
-bl64_check_parameter 'dev_lab_image' &&
-  bl64_check_export 'DEV_CICD_LAB_REGISTRY' &&
-  bl64_check_directory "$DEV_LAB_KUBE_HOME" &&
-  bl64_cnt_setup ||
-  exit $?
 
 bl64_msg_all_enable_verbose
-bl64_msg_show_batch_start 'lab'
-dev_lab_open "$dev_lab_image"
-bl64_msg_show_batch_finish $? 'lab'
+bl64_msg_show_batch_start 'dev-lab-kind'
+dev_lab_initialize &&
+  dev_lab_open "$dev_lab_image"
+bl64_msg_show_batch_finish $? 'dev-lab-kind'
