feat: update cli

diff --git a/src/minikube/bash/control b/src/minikube/bash/control
--- a/src/minikube/bash/control
+++ b/src/minikube/bash/control
@@ -29,14 +29,14 @@
 # Imports
 #
 
-# shellcheck source=SCRIPTDIR/../../../bin/dev-set
+# shellcheck source=bin/dev-set
 source ./bin/dev-set || exit 1
 
-# shellcheck source-path=SCRIPTDIR/../../../lib/bl64
+# shellcheck source=lib/bl64/bashlib64.bash
 source "${DEV_CICD_BASHLIB64}/bashlib64.bash" || { echo "Error: unable to load bashlib64" && exit 1; }
 
-# shellcheck source-path=SCRIPTDIR/../../gitops/bash
-source "${DEV_SRC}/gitops/bash-lib/setup" || { echo "Error: unable to load gitops-lib" && exit 1; }
+# shellcheck source=src/gitops/bash-lib/setup
+source "${DEV_SRC}/gitops/bash-lib/setup" || { echo "Error: unable to load bashlib64" && exit 1; }
 
 #
 # Globals
@@ -63,6 +63,8 @@ function minikube_control_node_get_names() {
     get nodes -o jsonpath="{.items[*].metadata.name}{'\n'}"
 }
 
+# Required to prevent false positive on YAML generated shell-env
+# shellcheck disable=SC2154
 function minikube_control_node_get_kubelet() {
   bl64_dbg_app_show_function
   "$MINIKUBE_CLUSTER_CONTROL_MINIKUBE_BIN" \
@@ -75,11 +77,15 @@ function minikube_control_node_get_kubelet() {
       '. + {"serverTLSBootstrap": true}'
 }
 
+# Required to prevent false positive on YAML generated shell-env
+# shellcheck disable=SC2154
 function minikube_control_node_restart() {
-  bl64_dbg_app_show_function
+  bl64_dbg_app_show_function "$@"
+  local node="$1"
   "$MINIKUBE_CLUSTER_CONTROL_MINIKUBE_BIN" \
     ssh \
     --profile="$MINIKUBE_CLUSTER_PROFILE" \
+    --node="$node" \
     "sudo systemctl daemon-reload; sudo systemctl restart kubelet"
 }
 
@@ -87,8 +93,10 @@ function minikube_control_certificate_approve() {
   bl64_dbg_app_show_function
   local certificate=''
   local certificate_list=''
+  local wait=5
 
   bl64_msg_show_task 'wait for new certificate requests'
+  sleep "$wait"
   while [[ -z "$certificate_list" ]]; do
     certificate_list="$(
       bl64_k8s_run_kubectl "$BL64_VAR_DEFAULT" \
@@ -111,6 +119,7 @@ function minikube_control_certificate_deploy() {
   local node_list=''
   local node=''
   local node_kubelet=''
+  local wait=5
   local -i status=0
 
   bl64_msg_show_task 'obtain cluster data'
@@ -122,12 +131,13 @@ function minikube_control_certificate_deploy() {
   bl64_k8s_run_kubectl \
     "$BL64_VAR_DEFAULT" \
     create configmap kubelet-config \
-    --dry-run -o yaml --from-literal=kubelet="$data_kubelet" |
+    --dry-run=client --output=yaml --from-literal=kubelet="$data_kubelet" |
     bl64_k8s_run_kubectl "$BL64_VAR_DEFAULT" \
       apply -f - ||
     return $?
 
   node_kubelet="$(bl64_fs_create_tmpfile)"
+  sleep "$wait"
   for node in $node_list; do
     bl64_msg_show_task "update node kubelet (${node})"
 
@@ -144,18 +154,31 @@ function minikube_control_certificate_deploy() {
     ((status != 0)) && break
 
     bl64_msg_show_subtask 'restart node kubelet'
-    minikube_control_node_restart
+    minikube_control_node_restart "$node"
     status=$?
     ((status != 0)) && break
+    sleep "$wait"
 
   done
   bl64_fs_rm_tmpfile "$node_kubelet"
   ((status != 0)) && return 1
-
   minikube_control_certificate_approve
 }
 
+# Required to prevent false positive on YAML generated shell-env
+# shellcheck disable=SC2154
 function minikube_control_cluster_start() {
+  bl64_dbg_app_show_function
+  case "$MINIKUBE_CLUSTER_DRIVER_NAME" in
+  'virtualbox') minikube_control_cluster_start_virtualbox ;;
+  'kvm2') minikube_control_cluster_start_kvm2 ;;
+  *) bl64_check_alert_parameter_invalid "$MINIKUBE_CLUSTER_DRIVER_NAME" ;;
+  esac
+}
+
+# Required to prevent false positive on YAML generated shell-env
+# shellcheck disable=SC2154
+function minikube_control_cluster_start_virtualbox() {
   bl64_dbg_app_show_function
   bl64_dbg_app_trace_start
   "$MINIKUBE_CLUSTER_CONTROL_MINIKUBE_BIN" \
@@ -171,6 +194,27 @@ function minikube_control_cluster_start() {
   bl64_dbg_app_trace_stop
 }
 
+# Required to prevent false positive on YAML generated shell-env
+# shellcheck disable=SC2154
+function minikube_control_cluster_start_kvm2() {
+  bl64_dbg_app_show_function
+  bl64_dbg_app_trace_start
+  "$MINIKUBE_CLUSTER_CONTROL_MINIKUBE_BIN" \
+    start \
+    --profile="$MINIKUBE_CLUSTER_PROFILE" \
+    --nodes="$K8S_CLUSTER_SIZE_NODES" \
+    --cpus="$K8S_CLUSTER_SIZE_CPUS" \
+    --memory="$K8S_CLUSTER_SIZE_MEMORY" \
+    --disk-size="$K8S_CLUSTER_SIZE_DISK_SIZE" \
+    --install-addons="$MINIKUBE_CLUSTER_ADDONS_INSTALL" \
+    --driver="$MINIKUBE_CLUSTER_DRIVER_NAME" \
+    --kubernetes-version="$K8S_CLUSTER_VERSION" \
+    --extra-disks="$K8S_CLUSTER_SIZE_EXTRA_DISKS"
+  bl64_dbg_app_trace_stop
+}
+
+# Required to prevent false positive on YAML generated shell-env
+# shellcheck disable=SC2154
 function minikube_control_cluster_show() {
   bl64_dbg_app_show_function
   bl64_dbg_app_trace_start
@@ -181,6 +225,8 @@ function minikube_control_cluster_show() {
   return 0
 }
 
+# Required to prevent false positive on YAML generated shell-env
+# shellcheck disable=SC2154
 function minikube_control_cluster_stop() {
   bl64_dbg_app_show_function
   bl64_dbg_app_trace_start
@@ -189,6 +235,20 @@ function minikube_control_cluster_stop() {
     'YES' &&
     "$MINIKUBE_CLUSTER_CONTROL_MINIKUBE_BIN" \
       stop \
+      --profile="$MINIKUBE_CLUSTER_PROFILE"
+  bl64_dbg_app_trace_stop
+}
+
+# Required to prevent false positive on YAML generated shell-env
+# shellcheck disable=SC2154
+function minikube_control_cluster_delete() {
+  bl64_dbg_app_show_function
+  bl64_dbg_app_trace_start
+  bl64_ui_ask_confirmation \
+    'Do you want to completely destroy the cluster?. Confirm by typing:' \
+    'YES' &&
+    "$MINIKUBE_CLUSTER_CONTROL_MINIKUBE_BIN" \
+      delete \
       --profile="$MINIKUBE_CLUSTER_PROFILE"
   bl64_dbg_app_trace_stop
 }
@@ -212,6 +272,7 @@ function minikube_control_initialize() {
   local configuration_minikube="etc/${environment}/minikube/cluster.yaml"
   local configuration_k8s="etc/${environment}/k8s/cluster.yaml"
 
+  # shellcheck disable=SC2015
   bl64_check_parameter 'command' &&
     bl64_check_parameter 'environment' ||
     { minikube_control_help && return 1; }
@@ -221,8 +282,8 @@ function minikube_control_initialize() {
     bl64_check_command "$MINIKUBE_CLUSTER_CONTROL_MINIKUBE_BIN" &&
     bl64_k8s_setup &&
     gitops_initialize &&
-    gitops_setup_import_etc "$configuration_minikube" &&
-    gitops_setup_import_etc "$configuration_k8s" ||
+    bl64_bsh_env_import_yaml "$configuration_minikube" &&
+    bl64_bsh_env_import_yaml "$configuration_k8s" ||
     return $?
 
   bl64_dbg_app_show_variables
@@ -249,12 +310,13 @@ function minikube_control_initialize() {
 #######################################
 function minikube_control_help() {
   bl64_msg_show_usage \
-    '<-s|-o|-p|-t> -e Environment [-V Verbose] [-D Debug] [-h]' \
+    '<-s|-o|-p|-d|-t> -e Environment [-V Verbose] [-D Debug] [-h]' \
     'Minikube cluster control wrapper' \
     '
     -s            : Start cluster
     -o            : Show cluster details
     -p            : Stop cluster
+    -d            : Delete (destroy) cluster
     -t            : Deploy Node Certificate
     ' '
     -h            : Show help
@@ -276,11 +338,12 @@ declare minikube_control_option=''
 declare minikube_control_environment="$BL64_VAR_NULL"
 
 (($# == 0)) && minikube_control_help && exit 1
-while getopts ':sopte:V:D:h' minikube_control_option; do
+while getopts ':sopdte:V:D:h' minikube_control_option; do
   case "$minikube_control_option" in
   s) minikube_control_command='cluster_start' ;;
   o) minikube_control_command='cluster_show' ;;
   p) minikube_control_command='cluster_stop' ;;
+  d) minikube_control_command='cluster_delete' ;;
   t) minikube_control_command='certificate_deploy' ;;
   e) minikube_control_environment="$OPTARG" ;;
   V) minikube_control_verbose="$OPTARG" ;;
@@ -294,7 +357,7 @@ minikube_control_initialize "$minikube_control_command" "$minikube_control_envir
 
 bl64_msg_show_batch_start "$minikube_control_command"
 case "$minikube_control_command" in
-'cluster_start' | 'cluster_show' | 'cluster_stop') "minikube_control_${minikube_control_command}" ;;
+'cluster_start' | 'cluster_show' | 'cluster_stop' | 'cluster_delete') "minikube_control_${minikube_control_command}" ;;
 'certificate_deploy') "minikube_control_${minikube_control_command}" ;;
 *) bl64_check_alert_parameter_invalid "$minikube_control_command" ;;
 esac
